### ISSUE TITLE
releasing 2.2.1

### ISSUE THREAD

**Issue by keighrim** [lapps/org.lappsgrid.maven.parent-pom#5]
I would like to suggest a release of 2.2.1 based on the commit d4bec27caf97d12c810a0e87ed5513457555bf3f, just fixing jackson security issue. 

I think updated vocabulary dependencies can be included in the next release.

**Comment by ksuderman** [comment]
Sounds good.  I will roll this out ASAP, which will likely be Sunday or Monday.

**Comment by ksuderman** [comment]
Version 2.2.1 should be available on Maven Central shortly.  I have also push 2.2.2-SNAPSHOT to the Sonatype SNAPSHOT repository.
